version: "3.7"
services:
  youdo-db:
    container_name: youdo-db
    restart: always
    image: postgres:10-alpine
    environment:
      POSTGRES_USER: youdo
      POSTGRES_PASSWORD: youdo
      POSTGRES_DB: youdo

  youdo-adminer:
    image: adminer
    container_name: youdo-adminer
    restart: always
    depends_on:
      - youdo-db
    ports:
      - 8081:8080

  youdo-api:
    image: bredda/youdo-api
    container_name: youdo-api
    environment:
      YOUDO_DB_URL: youdo-db
      YOUDO_DB_PORT: 5432
      YOUDO_DB_NAME: youdo
      YOUDO_DB_USER: youdo
      YOUDO_DB_PASSWORD: youdo
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      - youdo-db
    ports:
      - 8000:8000
